# Generated by Django 5.2.1 on 2025-06-08 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermodel',
            table=None,
        ),
    ]
