# Generated by Django 5.2.1 on 2025-06-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='publisherId',
            field=models.CharField(max_length=11),
        ),
    ]
