# Generated by Django 5.2.1 on 2025-06-10 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_usermodel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='username',
        ),
    ]
