# Generated by Django 5.2.1 on 2025-06-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_usermodel_username_usermodel_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='publisherUserName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='dept',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ENG', 'ENG'), ('LAW', 'LAW'), ('SWE', 'SWE'), ('ECO', 'ECO'), ('EEE', 'EEE'), ('BBA', 'BBA')], default='CSE', max_length=3),
        ),
    ]
