# Generated by Django 5.2.1 on 2025-06-13 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_items_publisherusername_alter_usermodel_dept'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='MU_id',
            new_name='mu_id',
        ),
    ]
