# Generated by Django 5.2.1 on 2025-06-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_mu_id_usermodel_mu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
