# Generated by Django 5.2.1 on 2025-06-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_usermodel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='mu_id',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
