# Generated by Django 5.2.1 on 2025-06-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_usermodel_mu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='dept',
            field=models.CharField(choices=[('CSE', 'CSE'), ('SWE', 'SWE'), ('ENG', 'ENG'), ('LLB', 'LLB'), ('ECO', 'ECO'), ('EEE', 'EEE'), ('BBA', 'BBA')], default='CSE', max_length=3),
        ),
    ]
