# Generated by Django 5.2.1 on 2025-06-13 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_usermodel_dept'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='completed',
            new_name='is_valid',
        ),
    ]
