# Generated by Django 5.2.1 on 2025-06-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_completed_usermodel_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='username',
            field=models.CharField(default='default_username', max_length=20),
            preserve_default=False,
        ),
    ]
