# Generated by Django 5.2.1 on 2025-06-14 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_usermodel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='dateTime',
        ),
        migrations.RemoveField(
            model_name='items',
            name='publisherId',
        ),
        migrations.RemoveField(
            model_name='items',
            name='publisherName',
        ),
        migrations.RemoveField(
            model_name='items',
            name='publisherUserName',
        ),
    ]
