# Generated by Django 5.2.1 on 2025-06-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_items_datetime_remove_items_publisherid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='publisherId',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='publisherName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='publisherUserName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
