# Generated by Django 5.2.1 on 2025-06-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_items_publisherid_items_publishername_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='type',
            field=models.CharField(choices=[('Found', 'Found'), ('Lost', 'Lost')], default='N/A'),
        ),
    ]
