# Generated by Django 5.2.1 on 2025-06-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_items_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='type',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Found', 'Found'), ('Lost', 'Lost')], default='N/A'),
        ),
    ]
