# Generated by Django 5.2.1 on 2025-06-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_items_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='dept',
            field=models.CharField(choices=[('N/A', 'N/A'), ('CSE', 'CSE'), ('SWE', 'SWE'), ('ENG', 'ENG'), ('LLB', 'LLB'), ('ECO', 'ECO'), ('EEE', 'EEE'), ('BBA', 'BBA')], default='N/A', max_length=3),
        ),
    ]
