# Generated by Django 5.2.1 on 2025-06-20 06:10

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_usermodel_dept'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_publisherId', models.CharField(blank=True, max_length=11, null=True)),
                ('original_publisherUserName', models.CharField(blank=True, max_length=50, null=True)),
                ('original_publisherName', models.CharField(blank=True, max_length=50, null=True)),
                ('original_itemType', models.CharField(choices=[('N/A', 'N/A'), ('Found', 'Found'), ('Lost', 'Lost')], default='N/A')),
                ('original_image', models.ImageField(blank=True, null=True, upload_to=app.models.images)),
                ('original_title', models.CharField(max_length=100)),
                ('original_description', models.TextField()),
                ('original_location', models.CharField(max_length=100)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
