# Generated by Django 5.2.1 on 2025-06-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_backup'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='original_item_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
