# Generated by Django 5.2.1 on 2025-06-23 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_backup_original_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='is_valid',
        ),
    ]
