# Generated by Django 5.2.1 on 2025-07-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_usermodel_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='original_itemType',
            field=models.CharField(choices=[('Select post type', 'Select post type'), ('Found Item', 'Found Item'), ('Lost Item', 'Lost Item')], default='N/A'),
        ),
        migrations.AlterField(
            model_name='items',
            name='type',
            field=models.CharField(choices=[('Select post type', 'Select post type'), ('Found Item', 'Found Item'), ('Lost Item', 'Lost Item')], default='Select post type'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='dept',
            field=models.CharField(choices=[('Select Department', 'Select Department'), ('CSE', 'CSE'), ('SWE', 'SWE'), ('ENG', 'ENG'), ('LLB', 'LLB'), ('ECO', 'ECO'), ('EEE', 'EEE'), ('BBA', 'BBA')], default='Select Department'),
        ),
    ]
