# Generated by Django 5.2.1 on 2025-07-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_backup_original_itemtype_alter_items_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='original_itemType',
            field=models.CharField(choices=[('Select post type', 'Select post type'), ('Found', 'Found'), ('Lost', 'Lost')], default='N/A'),
        ),
        migrations.AlterField(
            model_name='items',
            name='type',
            field=models.CharField(choices=[('Select post type', 'Select post type'), ('Found', 'Found'), ('Lost', 'Lost')], default='Select post type'),
        ),
    ]
