# Generated by Django 5.2.1 on 2025-07-13 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_backup_original_itemtype_alter_items_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(blank=True, max_length=50, null=True)),
                ('sender', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('default', 'default'), ('Found', 'Found'), ('Lost', 'Lost')], default='default')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accept', 'Accept'), ('Reject', 'Reject')], default='Pending')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.items')),
            ],
        ),
    ]
