# Generated by Django 5.2.1 on 2025-07-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_notificationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='type',
            field=models.CharField(choices=[('default', 'default'), ('claim_request', 'claim_request'), ('found_notification', 'found_notification')], default='default'),
        ),
    ]
