# Generated by Django 5.2.1 on 2025-07-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_notificationmodel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='recipient_muID',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='sender_muID',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
