# Generated by Django 5.2.1 on 2025-07-13 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_notificationmodel_recipient_muid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.items'),
        ),
    ]
