# Generated by Django 5.2.1 on 2025-07-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_notificationmodel_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationmodel',
            name='item',
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='item_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
