# Generated by Django 5.2.1 on 2025-07-13 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_remove_notificationmodel_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationmodel',
            name='item_ID',
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.items'),
        ),
    ]
