# Generated by Django 5.2.1 on 2025-07-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_notificationmodel_item_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='recipient',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='backup',
            name='recipient_muID',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='backup',
            name='sender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='backup',
            name='sender_muID',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
