# Generated by Django 5.2.1 on 2025-07-15 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_backup_recipient_backup_recipient_muid_backup_sender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationmodel',
            name='message',
        ),
    ]
