# Generated by Django 5.2.1 on 2025-07-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_remove_notificationmodel_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='is_read',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
